### ISSUE TITLE
Could not load: bgfx-shared-lib(Debug|Release).dll

### ISSUE THREAD

**Issue by rszemplinski** [zacharycarter/bgfx.nim#4]
When I run the program (more like attempt) I get this error that I don't know how to resolve. Any ideas on why this is happening?

Platform:
Windows 10

**Comment by treeform** [comment]
I managed to get it to work by grabbing this dll off the internet.

![image](https://user-images.githubusercontent.com/125948/74949763-08cb1600-53b3-11ea-8c3a-0d52a324bcc4.png)

https://github.com/jnadro/pybgfx/blob/master/pybgfx/bgfx-shared-libRelease.dll

It also needed SDL2 which can be found here: https://www.libsdl.org/release/SDL2-2.0.10-win32-x64.zip

**Comment by rszemplinski** [comment]
Dude, thank you so much. I'll check this out when I get home!!

**Comment by rszemplinski** [comment]
This worked! Thank you so much @treeform!!!
